### ISSUE TITLE
Install conda and obvious-ci from source

### ISSUE THREAD

**Issue by ocefpaf** [ocefpaf/centos64_conda_obvious-ci#1]
@pelson I started this repository to manage the docker image via a `Dockerfile` and automated build on dockerhub.  Just pinging you in case you are interested.

Things I want to change:
- Start from a "clean slate" Centos
- Add instruction for conda and obvious-ci installation in the `Dockerfile`

@rsignell-usgs This will improve the the IOOS channel maintainability and reproducibility in case someone else needs to follow what I am doing.

**Comment by pelson** [comment]
Thanks @ocefpaf. Good job! I should have published my Dockerfile with the images - my bad.
Neat that you've hooked it into dockerhub though - I've been meaning to look into how to do that.

Expect an email in the next few days regarding conda-forge. :wink:

**Comment by ocefpaf** [comment]
> I've been meaning to look into how to do that.

It is easy.  You just have to create the GitHub repository for the Dockerfile first (or leave the Dockerfile at conda-recipes-scitools) and then add the docker hook.

> Expect an email in the next few days regarding conda-forge. 

Looking forward to it!

**Comment by rsignell-usgs** [comment]
This is great. I'm cheering from the sidelines here!

**Comment by ocefpaf** [comment]
Done in https://registry.hub.docker.com/u/ocefpaf/centos64-conda-obvious-ci/dockerfile/

NB: Surprisingly the `centos:5` did not work!  Apparently that image does not have `GLIBC_2.7`.  But the `centos:6` works just fine in wakari.
